version: 2

project_name: academy

before:
  hooks:
    - go mod tidy

builds:
  - id: academy
    binary: academy
    main: ./cmd/academy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Perttulands/agent-academy/internal/cli.Version={{.Version}}
      - -X github.com/Perttulands/agent-academy/internal/cli.Commit={{.Commit}}
      - -X github.com/Perttulands/agent-academy/internal/cli.BuildDate={{.Date}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: git
