version: 2

project_name: ludus-magnus

before:
  hooks:
    - go mod tidy

builds:
  - id: ludus-magnus
    binary: ludus-magnus
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: git
